force-app/main/default/objects/Newsletter_Subscription__c/Newsletter_Subscription__c.object-meta.xml
<CustomObject>
    <label>Newsletter Subscription</label>
    <nameField>
        <displayFormat>NS-{0000}</displayFormat>
        <label>Newsletter Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Newsletter Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Newsletter_Subscription__c/fields/ActionLabel__c.field-meta.xml
<CustomField>
    <fullName>ActionLabel__c</fullName>
    <formula>CASE(Status__c, &quot;Active&quot;, &quot;Unsubscribe&quot;, &quot;Inactive&quot;, &quot;Re-subscribe&quot;, &quot;Subscribe&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ActionLabel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Newsletter_Title__c.field-meta.xml
<CustomField>
    <fullName>Newsletter_Title__c</fullName>
    <formula>Newsletter__r.Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Newsletter Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Signup__c.field-meta.xml
<CustomField>
    <fullName>Signup__c</fullName>
    <label>Signup</label>
    <referenceTo>Signup__c</referenceTo>
    <relationshipLabel>Newsletter Subscriptions</relationshipLabel>
    <relationshipName>Newsletter_Subscriptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Signup__c/Signup__c.object-meta.xml
<CustomObject>
    <label>Signup</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Signup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/datatableNewsletterCtlr.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class datatableNewsletterCtlr {
    @AuraEnabled
    public static List<Newsletter_Subscription__c> getMyData(String signupId)
    {
        List<Newsletter_Subscription__c> results = null;
        
        if (Schema.sObjectType.Newsletter_Subscription__c.fields.Newsletter_Title__c.isAccessible()
            && Schema.sObjectType.Newsletter_Subscription__c.fields.Status__c.isAccessible()
            && Schema.sObjectType.Newsletter_Subscription__c.fields.ActionLabel__c.isAccessible())
        {
            results = [SELECT Id, Name, Newsletter_Title__c, Status__c, ActionLabel__c
                       FROM Newsletter_Subscription__c
                       WHERE Signup__c = :signupId
                       ORDER BY Newsletter_Title__c];
        }
        
        return results;
    }
    
}