force-app/main/default/objects/Newsletter__c/Newsletter__c.object-meta.xml
<CustomObject>
    <label>Newsletter</label>
    <nameField>
        <displayFormat>NEWS-{0000}</displayFormat>
        <label>Newsletter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Newsletters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Newsletter__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/Newsletter_Subscription__c.object-meta.xml
<CustomObject>
    <label>Newsletter Subscription</label>
    <nameField>
        <displayFormat>NS-{0000}</displayFormat>
        <label>Newsletter Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Newsletter Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Newsletter__c.field-meta.xml
<CustomField>
    <fullName>Newsletter__c</fullName>
    <label>Newsletter</label>
    <referenceTo>Newsletter__c</referenceTo>
    <relationshipLabel>Newsletter Subscriptions</relationshipLabel>
    <relationshipName>Newsletter_Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Signup__c.field-meta.xml
<CustomField>
    <fullName>Signup__c</fullName>
    <label>Signup</label>
    <referenceTo>Signup__c</referenceTo>
    <relationshipLabel>Newsletter Subscriptions</relationshipLabel>
    <relationshipName>Newsletter_Subscriptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Newsletter_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Signup__c/Signup__c.object-meta.xml
<CustomObject>
    <label>Signup</label>
    <nameField>
        <displayFormat>SU-{0000}</displayFormat>
        <label>Signup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Signup__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Signup__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Signup__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <label>UniqueKey</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/datatableNewsletterCtlrTest.cls
@IsTest
public class datatableNewsletterCtlrTest
{
    @IsTest
    private static void testGetMyData()
    {
        String guid = GuidUtil.NewGuid();
        
        Signup__c s = new Signup__c(
            FirstName__c = 'TestFirst',
            LastName__c = 'TestLast',
            Email__c = 'test@example.com',
            UniqueKey__c = guid);
        
        insert s;
        
        Newsletter__c n = new Newsletter__c(
            Title__c = 'TestNewsletter');
        
        insert n;
        
        Newsletter_Subscription__c ns = new Newsletter_Subscription__c(
            Signup__c = s.Id,
            Newsletter__c = n.Id,
            Status__c = 'Active');
        
        insert ns;
        
        List<Newsletter_Subscription__c> subs = datatableNewsletterCtlr.getMyData(s.Id);
        
        System.assert(subs.size() > 0);
    }
}